// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fleetshift/v1/ocp_engine_callback_service.proto

package callback

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OCPEnginePhaseResultRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ElapsedSeconds int32                  `protobuf:"varint,4,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OCPEnginePhaseResultRequest) Reset() {
	*x = OCPEnginePhaseResultRequest{}
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCPEnginePhaseResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCPEnginePhaseResultRequest) ProtoMessage() {}

func (x *OCPEnginePhaseResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCPEnginePhaseResultRequest.ProtoReflect.Descriptor instead.
func (*OCPEnginePhaseResultRequest) Descriptor() ([]byte, []int) {
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP(), []int{0}
}

func (x *OCPEnginePhaseResultRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *OCPEnginePhaseResultRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OCPEnginePhaseResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OCPEnginePhaseResultRequest) GetElapsedSeconds() int32 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *OCPEnginePhaseResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OCPEnginePhaseResultRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type OCPEngineMilestoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Event          string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	ElapsedSeconds int32                  `protobuf:"varint,3,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Attempt        int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OCPEngineMilestoneRequest) Reset() {
	*x = OCPEngineMilestoneRequest{}
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCPEngineMilestoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCPEngineMilestoneRequest) ProtoMessage() {}

func (x *OCPEngineMilestoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCPEngineMilestoneRequest.ProtoReflect.Descriptor instead.
func (*OCPEngineMilestoneRequest) Descriptor() ([]byte, []int) {
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP(), []int{1}
}

func (x *OCPEngineMilestoneRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *OCPEngineMilestoneRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *OCPEngineMilestoneRequest) GetElapsedSeconds() int32 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *OCPEngineMilestoneRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type OCPEngineCompletionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	InfraId           string                 `protobuf:"bytes,2,opt,name=infra_id,json=infraId,proto3" json:"infra_id,omitempty"`
	ClusterUuid       string                 `protobuf:"bytes,3,opt,name=cluster_uuid,json=clusterUuid,proto3" json:"cluster_uuid,omitempty"`
	ApiServer         string                 `protobuf:"bytes,4,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	Kubeconfig        []byte                 `protobuf:"bytes,5,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	CaCert            []byte                 `protobuf:"bytes,6,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	SshPrivateKey     []byte                 `protobuf:"bytes,7,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	SshPublicKey      []byte                 `protobuf:"bytes,8,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"`
	Region            string                 `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	MetadataJson      []byte                 `protobuf:"bytes,10,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	RecoveryAttempted bool                   `protobuf:"varint,11,opt,name=recovery_attempted,json=recoveryAttempted,proto3" json:"recovery_attempted,omitempty"`
	ElapsedSeconds    int32                  `protobuf:"varint,12,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Attempt           int32                  `protobuf:"varint,13,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OCPEngineCompletionRequest) Reset() {
	*x = OCPEngineCompletionRequest{}
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCPEngineCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCPEngineCompletionRequest) ProtoMessage() {}

func (x *OCPEngineCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCPEngineCompletionRequest.ProtoReflect.Descriptor instead.
func (*OCPEngineCompletionRequest) Descriptor() ([]byte, []int) {
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP(), []int{2}
}

func (x *OCPEngineCompletionRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *OCPEngineCompletionRequest) GetInfraId() string {
	if x != nil {
		return x.InfraId
	}
	return ""
}

func (x *OCPEngineCompletionRequest) GetClusterUuid() string {
	if x != nil {
		return x.ClusterUuid
	}
	return ""
}

func (x *OCPEngineCompletionRequest) GetApiServer() string {
	if x != nil {
		return x.ApiServer
	}
	return ""
}

func (x *OCPEngineCompletionRequest) GetKubeconfig() []byte {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

func (x *OCPEngineCompletionRequest) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *OCPEngineCompletionRequest) GetSshPrivateKey() []byte {
	if x != nil {
		return x.SshPrivateKey
	}
	return nil
}

func (x *OCPEngineCompletionRequest) GetSshPublicKey() []byte {
	if x != nil {
		return x.SshPublicKey
	}
	return nil
}

func (x *OCPEngineCompletionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *OCPEngineCompletionRequest) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *OCPEngineCompletionRequest) GetRecoveryAttempted() bool {
	if x != nil {
		return x.RecoveryAttempted
	}
	return false
}

func (x *OCPEngineCompletionRequest) GetElapsedSeconds() int32 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *OCPEngineCompletionRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type OCPEngineFailureRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Phase             string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	FailureReason     string                 `protobuf:"bytes,3,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	FailureMessage    string                 `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	LogTail           string                 `protobuf:"bytes,5,opt,name=log_tail,json=logTail,proto3" json:"log_tail,omitempty"`
	RequiresDestroy   bool                   `protobuf:"varint,6,opt,name=requires_destroy,json=requiresDestroy,proto3" json:"requires_destroy,omitempty"`
	RecoveryAttempted bool                   `protobuf:"varint,7,opt,name=recovery_attempted,json=recoveryAttempted,proto3" json:"recovery_attempted,omitempty"`
	Attempt           int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OCPEngineFailureRequest) Reset() {
	*x = OCPEngineFailureRequest{}
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCPEngineFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCPEngineFailureRequest) ProtoMessage() {}

func (x *OCPEngineFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCPEngineFailureRequest.ProtoReflect.Descriptor instead.
func (*OCPEngineFailureRequest) Descriptor() ([]byte, []int) {
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP(), []int{3}
}

func (x *OCPEngineFailureRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *OCPEngineFailureRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OCPEngineFailureRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *OCPEngineFailureRequest) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *OCPEngineFailureRequest) GetLogTail() string {
	if x != nil {
		return x.LogTail
	}
	return ""
}

func (x *OCPEngineFailureRequest) GetRequiresDestroy() bool {
	if x != nil {
		return x.RequiresDestroy
	}
	return false
}

func (x *OCPEngineFailureRequest) GetRecoveryAttempted() bool {
	if x != nil {
		return x.RecoveryAttempted
	}
	return false
}

func (x *OCPEngineFailureRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type OCPEngineAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCPEngineAck) Reset() {
	*x = OCPEngineAck{}
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCPEngineAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCPEngineAck) ProtoMessage() {}

func (x *OCPEngineAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCPEngineAck.ProtoReflect.Descriptor instead.
func (*OCPEngineAck) Descriptor() ([]byte, []int) {
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP(), []int{4}
}

var File_fleetshift_v1_ocp_engine_callback_service_proto protoreflect.FileDescriptor

const file_fleetshift_v1_ocp_engine_callback_service_proto_rawDesc = "" +
	"\n" +
	"/fleetshift/v1/ocp_engine_callback_service.proto\x12\rfleetshift.v1\"\xc3\x01\n" +
	"\x1bOCPEnginePhaseResultRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0felapsed_seconds\x18\x04 \x01(\x05R\x0eelapsedSeconds\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\"\x93\x01\n" +
	"\x19OCPEngineMilestoneRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12'\n" +
	"\x0felapsed_seconds\x18\x03 \x01(\x05R\x0eelapsedSeconds\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\"\xce\x03\n" +
	"\x1aOCPEngineCompletionRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x19\n" +
	"\binfra_id\x18\x02 \x01(\tR\ainfraId\x12!\n" +
	"\fcluster_uuid\x18\x03 \x01(\tR\vclusterUuid\x12\x1d\n" +
	"\n" +
	"api_server\x18\x04 \x01(\tR\tapiServer\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x05 \x01(\fR\n" +
	"kubeconfig\x12\x17\n" +
	"\aca_cert\x18\x06 \x01(\fR\x06caCert\x12&\n" +
	"\x0fssh_private_key\x18\a \x01(\fR\rsshPrivateKey\x12$\n" +
	"\x0essh_public_key\x18\b \x01(\fR\fsshPublicKey\x12\x16\n" +
	"\x06region\x18\t \x01(\tR\x06region\x12#\n" +
	"\rmetadata_json\x18\n" +
	" \x01(\fR\fmetadataJson\x12-\n" +
	"\x12recovery_attempted\x18\v \x01(\bR\x11recoveryAttempted\x12'\n" +
	"\x0felapsed_seconds\x18\f \x01(\x05R\x0eelapsedSeconds\x12\x18\n" +
	"\aattempt\x18\r \x01(\x05R\aattempt\"\xad\x02\n" +
	"\x17OCPEngineFailureRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12%\n" +
	"\x0efailure_reason\x18\x03 \x01(\tR\rfailureReason\x12'\n" +
	"\x0ffailure_message\x18\x04 \x01(\tR\x0efailureMessage\x12\x19\n" +
	"\blog_tail\x18\x05 \x01(\tR\alogTail\x12)\n" +
	"\x10requires_destroy\x18\x06 \x01(\bR\x0frequiresDestroy\x12-\n" +
	"\x12recovery_attempted\x18\a \x01(\bR\x11recoveryAttempted\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\"\x0e\n" +
	"\fOCPEngineAck2\x84\x03\n" +
	"\x18OCPEngineCallbackService\x12\\\n" +
	"\x11ReportPhaseResult\x12*.fleetshift.v1.OCPEnginePhaseResultRequest\x1a\x1b.fleetshift.v1.OCPEngineAck\x12X\n" +
	"\x0fReportMilestone\x12(.fleetshift.v1.OCPEngineMilestoneRequest\x1a\x1b.fleetshift.v1.OCPEngineAck\x12Z\n" +
	"\x10ReportCompletion\x12).fleetshift.v1.OCPEngineCompletionRequest\x1a\x1b.fleetshift.v1.OCPEngineAck\x12T\n" +
	"\rReportFailure\x12&.fleetshift.v1.OCPEngineFailureRequest\x1a\x1b.fleetshift.v1.OCPEngineAckBWZUgithub.com/fleetshift/fleetshift-poc/fleetshift-server/gen/fleetshift/v1;fleetshiftv1b\x06proto3"

var (
	file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescOnce sync.Once
	file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescData []byte
)

func file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescGZIP() []byte {
	file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescOnce.Do(func() {
		file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetshift_v1_ocp_engine_callback_service_proto_rawDesc), len(file_fleetshift_v1_ocp_engine_callback_service_proto_rawDesc)))
	})
	return file_fleetshift_v1_ocp_engine_callback_service_proto_rawDescData
}

var file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleetshift_v1_ocp_engine_callback_service_proto_goTypes = []any{
	(*OCPEnginePhaseResultRequest)(nil), // 0: fleetshift.v1.OCPEnginePhaseResultRequest
	(*OCPEngineMilestoneRequest)(nil),   // 1: fleetshift.v1.OCPEngineMilestoneRequest
	(*OCPEngineCompletionRequest)(nil),  // 2: fleetshift.v1.OCPEngineCompletionRequest
	(*OCPEngineFailureRequest)(nil),     // 3: fleetshift.v1.OCPEngineFailureRequest
	(*OCPEngineAck)(nil),                // 4: fleetshift.v1.OCPEngineAck
}
var file_fleetshift_v1_ocp_engine_callback_service_proto_depIdxs = []int32{
	0, // 0: fleetshift.v1.OCPEngineCallbackService.ReportPhaseResult:input_type -> fleetshift.v1.OCPEnginePhaseResultRequest
	1, // 1: fleetshift.v1.OCPEngineCallbackService.ReportMilestone:input_type -> fleetshift.v1.OCPEngineMilestoneRequest
	2, // 2: fleetshift.v1.OCPEngineCallbackService.ReportCompletion:input_type -> fleetshift.v1.OCPEngineCompletionRequest
	3, // 3: fleetshift.v1.OCPEngineCallbackService.ReportFailure:input_type -> fleetshift.v1.OCPEngineFailureRequest
	4, // 4: fleetshift.v1.OCPEngineCallbackService.ReportPhaseResult:output_type -> fleetshift.v1.OCPEngineAck
	4, // 5: fleetshift.v1.OCPEngineCallbackService.ReportMilestone:output_type -> fleetshift.v1.OCPEngineAck
	4, // 6: fleetshift.v1.OCPEngineCallbackService.ReportCompletion:output_type -> fleetshift.v1.OCPEngineAck
	4, // 7: fleetshift.v1.OCPEngineCallbackService.ReportFailure:output_type -> fleetshift.v1.OCPEngineAck
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fleetshift_v1_ocp_engine_callback_service_proto_init() }
func file_fleetshift_v1_ocp_engine_callback_service_proto_init() {
	if File_fleetshift_v1_ocp_engine_callback_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetshift_v1_ocp_engine_callback_service_proto_rawDesc), len(file_fleetshift_v1_ocp_engine_callback_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetshift_v1_ocp_engine_callback_service_proto_goTypes,
		DependencyIndexes: file_fleetshift_v1_ocp_engine_callback_service_proto_depIdxs,
		MessageInfos:      file_fleetshift_v1_ocp_engine_callback_service_proto_msgTypes,
	}.Build()
	File_fleetshift_v1_ocp_engine_callback_service_proto = out.File
	file_fleetshift_v1_ocp_engine_callback_service_proto_goTypes = nil
	file_fleetshift_v1_ocp_engine_callback_service_proto_depIdxs = nil
}
