// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: fleetshift/v1/ocp_engine_callback_service.proto

package callback

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OCPEngineCallbackService_ReportPhaseResult_FullMethodName = "/fleetshift.v1.OCPEngineCallbackService/ReportPhaseResult"
	OCPEngineCallbackService_ReportMilestone_FullMethodName   = "/fleetshift.v1.OCPEngineCallbackService/ReportMilestone"
	OCPEngineCallbackService_ReportCompletion_FullMethodName  = "/fleetshift.v1.OCPEngineCallbackService/ReportCompletion"
	OCPEngineCallbackService_ReportFailure_FullMethodName     = "/fleetshift.v1.OCPEngineCallbackService/ReportFailure"
)

// OCPEngineCallbackServiceClient is the client API for OCPEngineCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OCPEngineCallbackServiceClient interface {
	ReportPhaseResult(ctx context.Context, in *OCPEnginePhaseResultRequest, opts ...grpc.CallOption) (*OCPEngineAck, error)
	ReportMilestone(ctx context.Context, in *OCPEngineMilestoneRequest, opts ...grpc.CallOption) (*OCPEngineAck, error)
	ReportCompletion(ctx context.Context, in *OCPEngineCompletionRequest, opts ...grpc.CallOption) (*OCPEngineAck, error)
	ReportFailure(ctx context.Context, in *OCPEngineFailureRequest, opts ...grpc.CallOption) (*OCPEngineAck, error)
}

type oCPEngineCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOCPEngineCallbackServiceClient(cc grpc.ClientConnInterface) OCPEngineCallbackServiceClient {
	return &oCPEngineCallbackServiceClient{cc}
}

func (c *oCPEngineCallbackServiceClient) ReportPhaseResult(ctx context.Context, in *OCPEnginePhaseResultRequest, opts ...grpc.CallOption) (*OCPEngineAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCPEngineAck)
	err := c.cc.Invoke(ctx, OCPEngineCallbackService_ReportPhaseResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCPEngineCallbackServiceClient) ReportMilestone(ctx context.Context, in *OCPEngineMilestoneRequest, opts ...grpc.CallOption) (*OCPEngineAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCPEngineAck)
	err := c.cc.Invoke(ctx, OCPEngineCallbackService_ReportMilestone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCPEngineCallbackServiceClient) ReportCompletion(ctx context.Context, in *OCPEngineCompletionRequest, opts ...grpc.CallOption) (*OCPEngineAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCPEngineAck)
	err := c.cc.Invoke(ctx, OCPEngineCallbackService_ReportCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCPEngineCallbackServiceClient) ReportFailure(ctx context.Context, in *OCPEngineFailureRequest, opts ...grpc.CallOption) (*OCPEngineAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OCPEngineAck)
	err := c.cc.Invoke(ctx, OCPEngineCallbackService_ReportFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OCPEngineCallbackServiceServer is the server API for OCPEngineCallbackService service.
// All implementations must embed UnimplementedOCPEngineCallbackServiceServer
// for forward compatibility.
type OCPEngineCallbackServiceServer interface {
	ReportPhaseResult(context.Context, *OCPEnginePhaseResultRequest) (*OCPEngineAck, error)
	ReportMilestone(context.Context, *OCPEngineMilestoneRequest) (*OCPEngineAck, error)
	ReportCompletion(context.Context, *OCPEngineCompletionRequest) (*OCPEngineAck, error)
	ReportFailure(context.Context, *OCPEngineFailureRequest) (*OCPEngineAck, error)
	mustEmbedUnimplementedOCPEngineCallbackServiceServer()
}

// UnimplementedOCPEngineCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOCPEngineCallbackServiceServer struct{}

func (UnimplementedOCPEngineCallbackServiceServer) ReportPhaseResult(context.Context, *OCPEnginePhaseResultRequest) (*OCPEngineAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPhaseResult not implemented")
}
func (UnimplementedOCPEngineCallbackServiceServer) ReportMilestone(context.Context, *OCPEngineMilestoneRequest) (*OCPEngineAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMilestone not implemented")
}
func (UnimplementedOCPEngineCallbackServiceServer) ReportCompletion(context.Context, *OCPEngineCompletionRequest) (*OCPEngineAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCompletion not implemented")
}
func (UnimplementedOCPEngineCallbackServiceServer) ReportFailure(context.Context, *OCPEngineFailureRequest) (*OCPEngineAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFailure not implemented")
}
func (UnimplementedOCPEngineCallbackServiceServer) mustEmbedUnimplementedOCPEngineCallbackServiceServer() {
}
func (UnimplementedOCPEngineCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeOCPEngineCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OCPEngineCallbackServiceServer will
// result in compilation errors.
type UnsafeOCPEngineCallbackServiceServer interface {
	mustEmbedUnimplementedOCPEngineCallbackServiceServer()
}

func RegisterOCPEngineCallbackServiceServer(s grpc.ServiceRegistrar, srv OCPEngineCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedOCPEngineCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OCPEngineCallbackService_ServiceDesc, srv)
}

func _OCPEngineCallbackService_ReportPhaseResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCPEnginePhaseResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCPEngineCallbackServiceServer).ReportPhaseResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCPEngineCallbackService_ReportPhaseResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCPEngineCallbackServiceServer).ReportPhaseResult(ctx, req.(*OCPEnginePhaseResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCPEngineCallbackService_ReportMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCPEngineMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCPEngineCallbackServiceServer).ReportMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCPEngineCallbackService_ReportMilestone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCPEngineCallbackServiceServer).ReportMilestone(ctx, req.(*OCPEngineMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCPEngineCallbackService_ReportCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCPEngineCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCPEngineCallbackServiceServer).ReportCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCPEngineCallbackService_ReportCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCPEngineCallbackServiceServer).ReportCompletion(ctx, req.(*OCPEngineCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCPEngineCallbackService_ReportFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OCPEngineFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCPEngineCallbackServiceServer).ReportFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OCPEngineCallbackService_ReportFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCPEngineCallbackServiceServer).ReportFailure(ctx, req.(*OCPEngineFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OCPEngineCallbackService_ServiceDesc is the grpc.ServiceDesc for OCPEngineCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OCPEngineCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetshift.v1.OCPEngineCallbackService",
	HandlerType: (*OCPEngineCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportPhaseResult",
			Handler:    _OCPEngineCallbackService_ReportPhaseResult_Handler,
		},
		{
			MethodName: "ReportMilestone",
			Handler:    _OCPEngineCallbackService_ReportMilestone_Handler,
		},
		{
			MethodName: "ReportCompletion",
			Handler:    _OCPEngineCallbackService_ReportCompletion_Handler,
		},
		{
			MethodName: "ReportFailure",
			Handler:    _OCPEngineCallbackService_ReportFailure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetshift/v1/ocp_engine_callback_service.proto",
}
