apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleetshift
resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/pvc.yaml
  - fleetshift-server/deployment.yaml
  - fleetshift-server/service.yaml
  - fleetshift-server/route-http.yaml
  - fleetshift-server/route-grpc.yaml
  - fleetshift-server/imagestreams.yaml
  - auth-setup/job.yaml
configMapGenerator:
  - name: fleetshift-server-config
    envs:
      - config.env
secretGenerator:
  - name: postgres-credentials
    envs:
      - secrets.env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
